"""Backend protocol used by the public API."""

from collections.abc import Mapping
from typing import Protocol

from soarm101_motion.types import HardwareState


class RobotBackend(Protocol):
    @property
    def is_connected(self) -> bool: ...

    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def read_joint_positions(self) -> Mapping[str, float]: ...

    def read_hardware_state(self) -> HardwareState: ...

    def write_joint_positions(self, positions: Mapping[str, float]) -> None: ...

    def enable_torque(self) -> None: ...

    def disable_torque(self) -> None: ...

    def stop(self) -> None: ...
